/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Piece, \'id\'>, schemaOptions: { title: \'NewPiece\', exclude: [ \'id\' ] })
 */
export interface NewPiece {
  [key: string]: object | any;


    /**
     * Share image file name
     */
    fileName: string;
    /**
     * Share name
     */
    name: string;
    /**
     * Share description
     */
    description?: string;
    /**
     * Share Rarity
     */
    rarity?: string;
    /**
     * Share issuer
     */
    issuer?: string;
    /**
     * Share signatures
     */
    signatures?: string;
    /**
     * Share quality of engraving
     */
    quality?: string;
    /**
     * Share overall appearance
     */
    appearance?: string;
    /**
     * Share condition
     */
    condition?: string;
    /**
     * Share date of issue
     */
    issueDate?: string;
    /**
     * Share price estimate
     */
    price?: number;
    /**
     * Share share country iso code
     */
    country?: string;
    /**
     * Share creation date
     */
    creationDate: Date;
    pieceFamilyId?: string;
    pieceCategoryId?: string;
    pieceSubCategoryId?: string;
}
