/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Piece, \'id\'>, schemaOptions: { title: \'NewPiece\', exclude: [ \'id\' ] })
 */
export interface NewPiece { 
  [key: string]: object | any;


    /**
     * Share name
     */
    name: string;
    /**
     * Share description
     */
    description?: string;
    /**
     * Rarity
     */
    rarity?: string;
    /**
     * The issuer
     */
    issuer?: string;
    /**
     * Signatures
     */
    signatures?: string;
    /**
     * Quality of engraving
     */
    quality?: string;
    /**
     * Overall appearance
     */
    appearance?: string;
    /**
     * Condition
     */
    condition?: string;
    /**
     * Date of issue
     */
    issueDate?: string;
    /**
     * Price estimate
     */
    price?: number;
    /**
     * Share country iso code
     */
    country?: string;
    pieceFamilyId?: string;
    pieceCategoryId?: string;
    pieceSubCategoryId?: string;
}

