/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<PieceCategory, \'id\'>, schemaOptions: { title: \'NewPieceCategory\', exclude: [ \'id\' ] })
 */
export interface NewPieceCategory { 
  [key: string]: object | any;


    /**
     * Piece category name
     */
    name: string;
    pieceFamilyId?: string;
}

