/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PieceSubCategory { 
  [key: string]: object | any;


    /**
     * Piece sub category indentifier
     */
    id?: string;
    /**
     * Piece sub category name
     */
    name: string;
    pieceCategoryId?: string;
}

