/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: PieceFamilyWithRelations, schemaOptions: { includeRelations: true })
 */
export interface PieceFamilyWithRelations { 
  [key: string]: object | any;


    /**
     * Piece family indentifier
     */
    id?: string;
    /**
     * Piece family name
     */
    name: string;
}

