/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PieceSubCategoryScopeFilter1 } from './pieceSubCategoryScopeFilter1';


export interface PieceSubCategoryIncludeFilterItems1 { 
    relation?: string;
    scope?: PieceSubCategoryScopeFilter1;
}

