/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PieceScopeFilter1 } from './pieceScopeFilter1';


export interface PieceIncludeFilterItems1 { 
    relation?: string;
    scope?: PieceScopeFilter1;
}

