/**
 * collector-api
 * Where collector lives
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<PieceCategory>, schemaOptions: { partial: true })
 */
export interface PieceCategoryPartial { 
  [key: string]: object | any;


    /**
     * Piece category indentifier
     */
    id?: string;
    /**
     * Piece category name
     */
    name?: string;
    pieceFamilyId?: string;
}

